name: Pull Request Checks
on:
  pull_request_target:
    branches:
    - main
    - more-fixes

jobs:
  Build-and-Test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install .[test]
    - run: pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=app tests/ -n auto | tee pytest-coverage.txt
    - uses: MishaKav/pytest-coverage-comment@main
  Check-Changelog-Project-Versions:
    name: Changelog and Project Versions Match
    runs-on: ubuntu-latest
    if: >-s
      ! github.event.pull_request.draft
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install .
    - shell: python
      run: |-
        import changelog, semver, sys

        with open( "CHANGELOG.md", "r" ) as fp:
          changes = changelog.load( fp )

        if not isinstance( changes[ 0 ][ "version" ], semver.Version ):
          print(
            '::error title="Unreleased" Version Invalid::Latest version in "CHANGELOG.md" '
              'is "Unreleased", which cannot be merged'
            flush = True,
            file = sys.stderr
          )
          sys.exit( 1 )

        if changes[ 0 ][ "version" ] != semver.Version.parse( changelog.__version__ ):
          print(
            "::error title=Version Mismatch::Project version and latest version in "
              '"CHANGELOG.md" do not match'
            flush = True,
            file = sys.stderr
          )
          sys.exit( 1 )
