name: Unit Testing
on:
  pull_request:
    branches: main
    paths:
    - src/**
    - pyproject.toml

jobs:
  Test:
    name: Install and Test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install -e .[test]
    - run: coverage run -m pytest --junitxml=pytest.xml
    - run: coverage xml
    - uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-xml-coverage-path: ./coverage.xml
        junitxml-path: ./pytest.xml
    - id: pylint
      shell: bash
      run: >-
        pylint src --msg-template
        '::{category} title=pylint,file={path},line={line},lineEnd={end_line},col={column},endColumn={end_column}::[{msg_id}] {msg}'
        | sed -r '/^::(error|warning)/! s/^::(\S+) title=pylint/::notice title=pylint - \1/g'
        | tee >(sed -rn 's/^Your code has been rated at (\S+).*$/score=\1/p' >> "$GITHUB_OUTPUT")
    - id: pylint-badge
      shell: bash
      run: |-
        printf -- '${{ steps.pylint.outputs.score }}' | jq -sRMr '
        ( split("/") | map(tonumber) | .[0] / .[1] * 100 ) as $percent |
        if $percent == 0 then "FF0000"
        elif 0 < $percent and $percent < 10 then "FF3300"
        elif 10 <= $percent and $percent < 20 then "ff6600"
        elif 20 <= $percent and $percent < 30 then "ff9900"
        elif 30 <= $percent and $percent < 40 then "FFCC00"
        elif 40 <= $percent and $percent < 50 then "FFFF00"
        elif 50 <= $percent and $percent < 60 then "ccff00"
        elif 60 <= $percent and $percent < 70 then "99ff00"
        elif 70 <= $percent and $percent < 80 then "ff6600"
        elif 80 <= $percent and $percent < 90 then "66ff00"
        elif 90 <= $percent and $percent < 100 then "33ff00"
        else "00FF00" end as $color |
        "url=https://img.shields.io/badge/\(
            "pylint score-\( $percent * 10 | round / 10 )-\( $color )"
          | @uri)"
        ' >> "$GITHUB_OUTPUT"
    - id: find-comment
      uses: peter-evans/find-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: github-actions
        body-includes: >-
          <!-- PyLint Comment: ${{ github.workflow }} -->
    - uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        edit-mode: replace
        body: |-
          <!-- PyLint Comment: ${{ github.workflow }} -->
          [![badge](${{ steps.pylint-badge.outputs.url }})])(${{ github.event.pull_request.diff_url }})